default_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logger_level: DEBUG
loggers:
  app:
    console_handler:
      enabled: false
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      level: INFO
    file_handler:
      backup_count: 3
      enabled: true
      filename: ./local/app.log
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      level: DEBUG
      max_bytes: 5242880
  
  ms_graph:
    console_handler:
      enabled: false
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      level: INFO
    file_handler:
      backup_count: 3
      enabled: true
      filename: ./local/ms_graph.log
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      level: WARNING
      max_bytes: 5242880